class CreateAccountPageObjects:
    create_account_button = '//button[@class="VfPpkd-LgbsSe VfPpkd-LgbsSe-OWXEXe-dgl2Hf ksBjEc lKxP2d LQeN7 FliLIb uRo0Xe TrZEUc Xf9GD"]'
    for_my_personal_use = '//li[@class="G3hhxb VfPpkd-StrnGf-rymPhb-ibnC6b"]'
    first_name_input = '//input[@id="firstName"]'
    last_name_input = '//input[@id="lastName"]'
    month_dropdown = '//select[@id="month"]'
    day_input = '//input[@id="day"]'
    year_input = '//input[@id="year"]'
    gender_dropdown = '//select[@id="gender"]'
    next_button = '//button[@class="VfPpkd-LgbsSe VfPpkd-LgbsSe-OWXEXe-k8QpJ VfPpkd-LgbsSe-OWXEXe-dgl2Hf nCP5yc AjY5Oe DuMIQc LQeN7 qIypjc TrZEUc lw1w4b"]'
    username_input = '//input[@name="Username"]'
    password_input = '//input[@name="Passwd"]'
    password_confirm_input = '//input[@name="PasswdAgain"]'
    show_password_check_box = '//input[@class="VfPpkd-muHVFf-bMcfAe"]'
    phone_number_input = '//input[@name="phoneNumberId"]'
